### ISSUE TITLE
Peer code review 27/04/2023

### ISSUE THREAD

**Issue by Theodoraldo** [Nasirkhan294/awesome-books-website#4]
- Wow, you have put much effort into implementing all these functionalities and UI. Great work 👏👏👏👏👌👌👌👌👌. 
- I suggest you add few functionalities to the project to improve it:

1.  The time under the navigation bar should be running time⏲⏲⌚⌚⌛⌛

**Comment by Nasirkhan294** [comment]
**Hi @Theodoraldo,** 

> - Thanks for bringing this to my attention. I would definitely consider your suggestion and update my project accordingly. 
> - Thanks again for your time and consideration!
